<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;
use think\Request;

class Goods extends Controller
{
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }
    public function index()
    {
        try {
            $dat = $this->request->get();
            $model = model('Good');
            $data = $model->query($dat);
            $count = $data->total();
            $goods = $data->items();
            if($count > 0 && count($goods)>0 ){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'数据获取成功',
                    'data'=>$goods,
                    'count'=>$count
                ]);
            }else{
                return json([
                    'code'=>config('code.fail'),
                    'msg'=>'数据获取失败'
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fail'),
                'msg'=>'服务器错误，联系管理员'
            ]);
        }


    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $data=$this->request->post();
        $model = model('Goods');
        $result=$model->goodsinsert($data);
        if($result > 0){
            return json([
                'code'=>config('code.success'),
                'msg'=>'商品插入成功'
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'商品插入失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        try{
            $model=model('Good');
            $result=$model->del($id);
            if($result>0){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'数据删除成功'
                ]);
            }else{
                return json([
                    'code'=>config('code.fail'),
                    'msg'=>'数据删除失败'
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fail'),
                'msg'=>'服务器错误，请联系管理员'
            ]);
        }

    }
}
